trigger:
  - main

pool:
  name: backend-agent

variables:
  SSH_CONNECTION: 'backendvm-ssh'
  APP_DIR:        '/app'
  SERVICE_NAME:   'chatapp.service'

stages:
- stage: Deploy
  jobs:
  - job: PushAndDeploy
    displayName: Copy & Deploy ChatApp
    steps:

      # 1) checkout
      - checkout: self

      # 2) copy all files to /app
      - task: CopyFilesOverSSH@0
        displayName: Copy code to $(APP_DIR)
        inputs:
          sshEndpoint: $(SSH_CONNECTION)
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: '**'
          targetFolder: '$(APP_DIR)'

      