trigger:
  - main

pool:
  name: remote-agent   # your self-hosted agent pool

variables:
  SSH_CONNECTION: 'backendvm-ssh'
  APP_DIR: '/app'

stages:
  - stage: Deploy
    displayName: Deploy ChatApp to Backend VM
    jobs:
      - job: PushAndDeploy
        displayName: Copy & Deploy ChatApp
        steps:
          - checkout: self

          - task: CopyFilesOverSSH@0
            displayName: Copy code to $(APP_DIR)
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: '**'
              targetFolder: '$(APP_DIR)'
              cleanTargetFolder: false

          - task: SSH@0
            displayName: Install Python dependencies
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                set -e

                echo "Entering $(APP_DIR)"
                cd $(APP_DIR)

                echo "Creating venv if it doesn't exist..."
                if [ ! -d venv ]; then
                  python3 -m venv venv
                fi

                echo "Activating venv and upgrading pip..."
                # shellcheck disable=SC1091
                source venv/bin/activate
                pip install --upgrade pip

                echo "Installing requirements.txt..."
                pip install -r requirements.txt

          - task: SSH@0
            displayName: Run makemigrations
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                set -e
                cd $(APP_DIR)/fundoo
                source /app/venv/bin/activate
                python3 manage.py makemigrations --noinput

          - task: SSH@0
            displayName: Apply migrations
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                set -e
                cd $(APP_DIR)/fundoo
                source /app/venv/bin/activate
                python3 manage.py migrate --noinput

          - task: SSH@0
            displayName: Restart chatapp.service
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                echo "Restarting chatapp.service..."
                sudo systemctl restart chatapp.service
