trigger:
  - main

pool:
  name: remote-agent   # your self-hosted agent pool

variables:
  # the name of the SSH service connection you created in Project → Service Connections
  SSH_CONNECTION: 'backendvm-ssh'
  # where your app lives on the remote VM
  APP_DIR: '/app'

stages:
  - stage: Deploy
    displayName: Deploy ChatApp to Backend VM
    jobs:
      - job: PushAndDeploy
        displayName: Copy & Deploy ChatApp
        steps:

          # 1) Checkout your code
          - checkout: self

          # 2) Copy code to the VM via SCP
          - task: CopyFilesOverSSH@0
            displayName: Copy code to $(APP_DIR)
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              sourceFolder: '$(Build.SourcesDirectory)'
              contents: '**'
              targetFolder: '$(APP_DIR)'
              cleanTargetFolder: false

          # 3) Install requirements inside the existing venv
          - task: SSH@0
            displayName: Install Python dependencies
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                set -e
                echo "Installing Python dependencies..."
                cd $(APP_DIR)
                source venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt

          # 4) makemigrations
          - task: SSH@0
            displayName: Run makemigrations
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                set -e
                echo "Running makemigrations..."
                cd $(APP_DIR)/fundoo
                source /app/venv/bin/activate
                python3 manage.py makemigrations --noinput

          # 5) migrate
          - task: SSH@0
            displayName: Apply migrations
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                set -e
                echo "Applying migrations..."
                cd $(APP_DIR)/fundoo
                source /app/venv/bin/activate
                python3 manage.py migrate --noinput

          # 6) restart the systemd service
          - task: SSH@0
            displayName: Restart chatapp.service
            inputs:
              sshEndpoint: $(SSH_CONNECTION)
              runOptions: inline
              inline: |
                echo "Restarting chatapp.service..."
                sudo systemctl restart chatapp.service

        # you can add post-job notifications or conditions here
