trigger:
  - main

pool:
  name: remote-agrnt-pool

variables:
  SSH_CONNECTION: 'backendvm-ssh'
  APP_DIR: '/app'
  SERVICE_NAME: 'chatapp.service'

stages:
- stage: Deploy
  jobs:
  - job: PushAndDeploy
    displayName: Copy & Deploy ChatApp
    steps:

      # 1) checkout
      - checkout: self
        clean: true

      # 2) copy all files to /app
      - task: CopyFilesOverSSH@0
        displayName: Copy code to $(APP_DIR)
        inputs:
          sshEndpoint: $(SSH_CONNECTION)
          sourceFolder: '$(Build.SourcesDirectory)'
          contents: '**'
          targetFolder: '$(APP_DIR)'

      # 3) SSH into VM and install dependencies
      - task: SSH@0
        displayName: Install requirements
        inputs:
          sshEndpoint: $(SSH_CONNECTION)
          runOptions: 'inline'
          inline: |
            cd $(APP_DIR)
            source venv/bin/activate
            pip3 install -r requirements.txt
            deactivate

      - task: SSH@0
        inputs:
          sshEndpoint: 'backendvm-ssh'
          runOptions: 'inline'
          inline: |
            cd $(APP_DIR)
            source venv/bin/activate
            cd fundoo
            python3 manage.py migrate
            cd ..
            deactivate

      - task: SSH@0
        inputs:
          sshEndpoint: 'backendvm-ssh'
          runOptions: 'inline'
          inline: |
            sudo systemctl restart $(SERVICE_NAME)
           