trigger:
- main

pool:
  name: 'remote-agent'   # or your self-hosted agent pool

variables:
  APP_DIR: '/app'

steps:
# 1) Checkout your repo
- checkout: self

# 2) Copy everything to the remote VM
- task: CopyFilesOverSSH@0
  displayName: 'Copy code to backend VM'
  inputs:
    sshEndpoint: 'backendvm-ssh'       # the service connection you just created
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
      **/*
    targetFolder: '$(APP_DIR)'
    cleanTargetFolder: true

# 3) Install deps, migrate, restart
- task: SSH@0
  displayName: 'Install Dependencies on backend VM'
  inputs:
    sshEndpoint: 'backendvm-ssh'
    runOptions: 'commands'
    commands: |
      set -e
      cd $(APP_DIR)
      source venv/bin/activate
      pip install -r requirements.txt

- task: SSH@0
  displayName: 'Run Migrations on backend VM'
  inputs:
    sshEndpoint: 'backendvm-ssh'
    runOptions: 'commands'
    commands: |
      set -e
      cd $(APP_DIR)/fundoo
      source ../venv/bin/activate
      python3 manage.py makemigrations
      python3 manage.py migrate

- task: SSH@0
  displayName: 'Restart chatapp.service'
  inputs:
    sshEndpoint: 'backendvm-ssh'
    runOptions: 'commands'
    commands: |
      sudo systemctl restart chatapp.service
